### ISSUE TITLE
emails are sent out with certain messages - especially "you got feedback"

### ISSUE THREAD

**Issue by theTrueMikeBrown** [theTrueMikeBrown/PlaytestHub#56]
users will have to opt in for this.

**Comment by theTrueMikeBrown** [comment]
I have made it so that all messages are also emails, and that users opt into them

**Comment by bcompter** [comment]
Let me know when this is live.

**Comment by theTrueMikeBrown** [comment]
it is already live - you just need to check the box to enable it in your
user profile.

**Comment by theTrueMikeBrown** [comment]
https://playtesthub.firebaseapp.com/editUser
the check box is labeled:  "Forward all messages to my email account"
